// Code generated by Slice Machine. DO NOT EDIT.

import TessaViergeverProfileCard from "./TessaViergeverProfileCard/index.svelte";

export const components = {
  tessa_viergever_profile_card: TessaViergeverProfileCard,
};
