// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

interface KaasDocumentData {}

/**
 * KAAS🧀 document from Prismic
 *
 * - **API ID**: `kaas`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KaasDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<KaasDocumentData>, "kaas", Lang>;

export type AllDocumentTypes = HomeDocument | KaasDocument;

/**
 * Primary content in *Menu → Items*
 */
export interface MenuSliceDefaultItem {
  /**
   * profiel foto field in *Menu → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.items[].profiel_foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profiel_foto: prismic.ImageField<never>;
}

/**
 * Default variation for Menu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MenuSliceDefaultItem>
>;

/**
 * Slice variation for *Menu*
 */
type MenuSliceVariation = MenuSliceDefault;

/**
 * Menu Shared Slice
 *
 * - **API ID**: `menu`
 * - **Description**: Menu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuSlice = prismic.SharedSlice<"menu", MenuSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      KaasDocument,
      KaasDocumentData,
      AllDocumentTypes,
      MenuSlice,
      MenuSliceDefaultItem,
      MenuSliceVariation,
      MenuSliceDefault,
    };
  }
}
