// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = TessaViergeverProfileCardSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Name field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *TessaViergeverProfileCard → Primary*
 */
export interface TessaViergeverProfileCardSliceDefaultPrimary {
  /**
   * Name field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tessa_viergever_profile_card.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Profile picture field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tessa_viergever_profile_card.primary.profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * Age field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Leeftijd
   * - **API ID Path**: tessa_viergever_profile_card.primary.age
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  age: prismic.NumberField;

  /**
   * Hobbies field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hobbies
   * - **API ID Path**: tessa_viergever_profile_card.primary.hobbies
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hobbies: prismic.RichTextField;

  /**
   * Instagram field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tessa_viergever_profile_card.primary.instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * LinkedIn field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tessa_viergever_profile_card.primary.linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * Github field in *TessaViergeverProfileCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tessa_viergever_profile_card.primary.github
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;
}

/**
 * Default variation for TessaViergeverProfileCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TessaViergeverProfileCardSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<TessaViergeverProfileCardSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *TessaViergeverProfileCard*
 */
type TessaViergeverProfileCardSliceVariation =
  TessaViergeverProfileCardSliceDefault;

/**
 * TessaViergeverProfileCard Shared Slice
 *
 * - **API ID**: `tessa_viergever_profile_card`
 * - **Description**: TessaViergeverProfileCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TessaViergeverProfileCardSlice = prismic.SharedSlice<
  "tessa_viergever_profile_card",
  TessaViergeverProfileCardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      TessaViergeverProfileCardSlice,
      TessaViergeverProfileCardSliceDefaultPrimary,
      TessaViergeverProfileCardSliceVariation,
      TessaViergeverProfileCardSliceDefault,
    };
  }
}
